[versions]

jmhVersion = "1.37"

[libraries]

javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
jmh-core = { module = 'org.openjdk.jmh:jmh-core', version.ref = "jmhVersion" }
jmh-generator-annprocess = { module = 'org.openjdk.jmh:jmh-generator-annprocess', version.ref = "jmhVersion" }
jmh-generator-bytecote = { module = 'org.openjdk.jmh:jmh-generator-bytecode', version.ref = "jmhVersion" }

[bundles]

jmh = [
    "jmh-core",
    "jmh-generator-annprocess",
    "jmh-generator-bytecote"
]